version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    groups: # grupperer alle endringer til én enkelt PR
      uv:
        patterns:
        - '*'