project:
  type: website
  render:
    - "index.qmd"
    - "datakvalitet.qmd"

date: now
date-format: "DD.MM.YYYY HH:mm:ss z"
published-title: "Sist oppdatert"

website:
  title: "Team Pia"
  repo-url: https://github.com/navikt/fia-datafortelling
  search:
    location: navbar
    type: overlay
  navbar:
    background: primary
    logo: assets/nav_logo_hvit.png
    logo-alt: "Logo til NAV - Arbeids- og velferdsetaten"
    left:
      - text: Startside
        href: index.qmd
      - text: Datakvalitet
        href: datakvalitet.qmd
    right:
      - icon: people-fill
        target: _blank
        text: Ansvarlig team hos NAV
        aria-label: Ansvarlig team hos NAV
        href: https://teamkatalog.nav.no/team/b347ac99-c382-4e5a-a1dd-532e91110e2a
      - icon: slack
        target: _blank
        aria-label: Slack kanal for kontakt
        href: https://nav-it.slack.com/archives/C02DL347ZT2 
      - icon: github
        target: _blank
        aria-label: Kildekode
        href: https://github.com/orgs/navikt/teams/pia
  page-footer:
    background: primary
    foreground: white
    center:
      - text: Vi ønsker tilbakemelding fra dere! Meld inn forslag til datafortellingen <u>her</u>
        target: _blank
        href: https://jira.adeo.no/plugins/servlet/desk/portal/541/create/4362
  announcement:
    type: danger
    icon: info-circle
    content: "**NB!** - Dette er ikke offisiell statistikk og må ikke deles utenfor Nav."
    position: above-navbar
    dismissable: true

execute:
    echo: false
    warning: false
    daemon: false

format:
  html:
    grid:
      body-width: 900px # default: 800px
      sidebar-width: 200px # default: 250px
      margin-width: 200px # default: 250px
    toc: true
    toc-title: Indeks
    theme:
      light: 
        - flatly
      dark:
        - darkly