project:
  execute-dir: project # Ungår problemer med path, execute alltid fra prosjekt (rotmappe) ikke fra f.eks src/quarto/samarbeid om vi renderer en fil i undermapper
  type: website
  output-dir: pages
  render:
    - index.qmd

    - datafortelling/sak/innhold.qmd
    - datafortelling/sak/norge.qmd
    - datafortelling/sak/agder.qmd
    - datafortelling/sak/innlandet.qmd
    - datafortelling/sak/more_og_romsdal.qmd
    - datafortelling/sak/nordland.qmd
    - datafortelling/sak/oslo.qmd
    - datafortelling/sak/ost-viken.qmd
    - datafortelling/sak/rogaland.qmd
    - datafortelling/sak/troms_og_finnmark.qmd
    - datafortelling/sak/trondelag.qmd
    - datafortelling/sak/vest-viken.qmd
    - datafortelling/sak/vestfold_og_telemark.qmd
    - datafortelling/sak/vestland.qmd

    - datafortelling/samarbeid/innhold.qmd
    - datafortelling/samarbeid/norge.qmd
    - datafortelling/samarbeid/agder.qmd
    - datafortelling/samarbeid/innlandet.qmd
    - datafortelling/samarbeid/more_og_romsdal.qmd
    - datafortelling/samarbeid/nordland.qmd
    - datafortelling/samarbeid/oslo.qmd
    - datafortelling/samarbeid/ost-viken.qmd
    - datafortelling/samarbeid/rogaland.qmd
    - datafortelling/samarbeid/troms_og_finnmark.qmd
    - datafortelling/samarbeid/trondelag.qmd
    - datafortelling/samarbeid/vest-viken.qmd
    - datafortelling/samarbeid/vestfold_og_telemark.qmd
    - datafortelling/samarbeid/vestland.qmd

    - datafortelling/samarbeidsplan/innhold.qmd
    - datafortelling/samarbeidsplan/norge.qmd
    - datafortelling/samarbeidsplan/agder.qmd
    - datafortelling/samarbeidsplan/innlandet.qmd
    - datafortelling/samarbeidsplan/more_og_romsdal.qmd
    - datafortelling/samarbeidsplan/nordland.qmd
    - datafortelling/samarbeidsplan/oslo.qmd
    - datafortelling/samarbeidsplan/ost-viken.qmd
    - datafortelling/samarbeidsplan/rogaland.qmd
    - datafortelling/samarbeidsplan/troms_og_finnmark.qmd
    - datafortelling/samarbeidsplan/trondelag.qmd
    - datafortelling/samarbeidsplan/vest-viken.qmd
    - datafortelling/samarbeidsplan/vestfold_og_telemark.qmd
    - datafortelling/samarbeidsplan/vestland.qmd


date: now
date-format: "DD.MM.YYYY HH:mm:ss z"
published-title: "Sist oppdatert"

website:
  title: "Fia - datafortelling"
  repo-url: https://github.com/navikt/fia-datafortelling
  search:
    location: navbar
    type: overlay
  navbar:
    background: primary
    logo: assets/nav_logo_hvit.png
    logo-alt: "Logo til NAV - Arbeids- og velferdsetaten"
    left:
      - text: Saksflyt
        menu:
        - href: datafortelling/sak/norge.qmd
          text: Hele Norge
        - href: datafortelling/sak/agder.qmd
          text: Agder
        - href: datafortelling/sak/innlandet.qmd
          text: Innlandet
        - href: datafortelling/sak/more_og_romsdal.qmd
          text: Møre og Romsdal
        - href: datafortelling/sak/nordland.qmd
          text: Nordland
        - href: datafortelling/sak/oslo.qmd
          text: Oslo
        - href: datafortelling/sak/ost-viken.qmd
          text: Øst-Viken
        - href: datafortelling/sak/rogaland.qmd
          text: Rogaland
        - href: datafortelling/sak/troms_og_finnmark.qmd
          text: Troms og Finnmark
        - href: datafortelling/sak/trondelag.qmd
          text: Trøndelag
        - href: datafortelling/sak/vest-viken.qmd
          text: Vest-Viken
        - href: datafortelling/sak/vestfold_og_telemark.qmd
          text: Vestfold og Telemark
        - href: datafortelling/sak/vestland.qmd
          text: Vestland
      - text: Samarbeid
        menu:
        - href: datafortelling/samarbeid/norge.qmd
          text: Hele Norge
        - href: datafortelling/samarbeid/agder.qmd
          text: Agder
        - href: datafortelling/samarbeid/innlandet.qmd
          text: Innlandet
        - href: datafortelling/samarbeid/more_og_romsdal.qmd
          text: Møre og Romsdal
        - href: datafortelling/samarbeid/nordland.qmd
          text: Nordland
        - href: datafortelling/samarbeid/oslo.qmd
          text: Oslo
        - href: datafortelling/samarbeid/ost-viken.qmd
          text: Øst-Viken
        - href: datafortelling/samarbeid/rogaland.qmd
          text: Rogaland
        - href: datafortelling/samarbeid/troms_og_finnmark.qmd
          text: Troms og Finnmark
        - href: datafortelling/samarbeid/trondelag.qmd
          text: Trøndelag
        - href: datafortelling/samarbeid/vest-viken.qmd
          text: Vest-Viken
        - href: datafortelling/samarbeid/vestfold_og_telemark.qmd
          text: Vestfold og Telemark
        - href: datafortelling/samarbeid/vestland.qmd
          text: Vestland
      - text: Samarbeidsplan
        menu:
        - href: datafortelling/samarbeidsplan/norge.qmd
          text: Hele Norge
        - href: datafortelling/samarbeidsplan/agder.qmd
          text: Agder
        - href: datafortelling/samarbeidsplan/innlandet.qmd
          text: Innlandet
        - href: datafortelling/samarbeidsplan/more_og_romsdal.qmd
          text: Møre og Romsdal
        - href: datafortelling/samarbeidsplan/nordland.qmd
          text: Nordland
        - href: datafortelling/samarbeidsplan/oslo.qmd
          text: Oslo
        - href: datafortelling/samarbeidsplan/ost-viken.qmd
          text: Øst-Viken
        - href: datafortelling/samarbeidsplan/rogaland.qmd
          text: Rogaland
        - href: datafortelling/samarbeidsplan/troms_og_finnmark.qmd
          text: Troms og Finnmark
        - href: datafortelling/samarbeidsplan/trondelag.qmd
          text: Trøndelag
        - href: datafortelling/samarbeidsplan/vest-viken.qmd
          text: Vest-Viken
        - href: datafortelling/samarbeidsplan/vestfold_og_telemark.qmd
          text: Vestfold og Telemark
        - href: datafortelling/samarbeidsplan/vestland.qmd
          text: Vestland
    right:
      - icon: people-fill
        target: _blank
        text: Ansvarlig team hos NAV
        aria-label: Ansvarlig team hos NAV
        href: https://teamkatalog.nav.no/team/b347ac99-c382-4e5a-a1dd-532e91110e2a
      - icon: slack
        target: _blank
        aria-label: Slack kanal for kontakt
        href: https://nav-it.slack.com/archives/C02DL347ZT2 
      - icon: github
        target: _blank
        aria-label: Kildekode
        href: https://github.com/orgs/navikt/teams/pia
  page-footer:
    background: primary
    foreground: white
    center:
      - text: Vi ønsker tilbakemelding fra dere! Meld inn forslag til datafortellingen <u>her</u>
        target: _blank
        href: https://jira.adeo.no/plugins/servlet/desk/portal/541/create/4362
  announcement:
    type: danger
    icon: info-circle
    content: "**NB!** - Dette er ikke offisiell statistikk og må ikke deles utenfor Nav."
    position: above-navbar
    dismissable: true

execute:
    echo: false
    warning: false
    daemon: false

format:
  html:
    grid:
      body-width: 900px # default: 800px
      sidebar-width: 200px # default: 250px
      margin-width: 200px # default: 250px
    toc: true
    toc-title: Indeks
    theme:
      light: 
        - flatly
      dark:
        - darkly