project:
  type: website
  output-dir: _site
  execute-dir: project

date: now
date-format: "DD.MM.YYYY HH:mm:ss z"
published-title: "Sist oppdatert"

website:
  title: "Team Pia"
  repo-url: https://github.com/navikt/fia-datafortelling
  search:
    location: navbar
    type: overlay
  navbar:
    background: primary
    logo: assets/nav_logo_hvit.png
    logo-alt: "Logo til NAV - Arbeids- og velferdsetaten"
    left:
      - text: Startside
        href: index.qmd
      - text: Datakvalitet
        href: datafortellinger/datakvalitet.qmd
      - text: Ny prosess i Fia
        href: datafortellinger/endret_prosess.qmd
      - text: Fia
        menu:
          - datafortellinger/fia/nasjonalt.qmd
          - datafortellinger/fia/agder.qmd
          - datafortellinger/fia/innlandet.qmd
          - datafortellinger/fia/møre_og_romsdal.qmd
          - datafortellinger/fia/nordland.qmd
          - datafortellinger/fia/oslo.qmd
          - datafortellinger/fia/øst-viken.qmd
          - datafortellinger/fia/rogaland.qmd
          - datafortellinger/fia/troms_og_finnmark.qmd
          - datafortellinger/fia/trøndelag.qmd
          - datafortellinger/fia/vest-viken.qmd
          - datafortellinger/fia/vestfold_og_telemark.qmd
          - datafortellinger/fia/vestland.qmd
      - text: Ia-tjenester
        menu:
          - datafortellinger/ia_tjenester//nasjonalt.qmd
          - datafortellinger/ia_tjenester//agder.qmd
          - datafortellinger/ia_tjenester//innlandet.qmd
          - datafortellinger/ia_tjenester//møre_og_romsdal.qmd
          - datafortellinger/ia_tjenester//nordland.qmd
          - datafortellinger/ia_tjenester//oslo.qmd
          - datafortellinger/ia_tjenester//øst-viken.qmd
          - datafortellinger/ia_tjenester//rogaland.qmd
          - datafortellinger/ia_tjenester//troms_og_finnmark.qmd
          - datafortellinger/ia_tjenester//trøndelag.qmd
          - datafortellinger/ia_tjenester//vest-viken.qmd
          - datafortellinger/ia_tjenester//vestfold_og_telemark.qmd
          - datafortellinger/ia_tjenester//vestland.qmd
    right:
      - icon: people-fill
        target: _blank
        text: Ansvarlig team hos NAV
        aria-label: Ansvarlig team hos NAV
        href: https://teamkatalog.nav.no/team/b347ac99-c382-4e5a-a1dd-532e91110e2a
      - icon: slack
        target: _blank
        aria-label: Slack kanal for kontakt
        href: https://nav-it.slack.com/archives/C02DL347ZT2 
      - icon: github
        target: _blank
        aria-label: Kildekode
        href: https://github.com/orgs/navikt/teams/pia
  page-footer:
    background: primary
    foreground: white
    center:
      - text: Vi ønsker tilbakemelding fra dere! Meld inn forslag til datafortellingen <u>her</u>
        target: _blank
        href: https://jira.adeo.no/plugins/servlet/desk/portal/541/create/4362
  announcement:
    type: danger
    icon: info-circle
    content: "**NB!** - Dette er ikke offisiell statistikk og må ikke deles utenfor Nav."
    position: above-navbar
    dismissable: true

execute:
    echo: false
    warning: false
    daemon: false

format:
  html:
    grid: 
      body-width: 900px # default: 800px
      sidebar-width: 200px # default: 250px
      margin-width: 200px # default: 250px
    toc: true
    toc-title: Indeks
    theme:
      light: 
        - flatly
      dark:
        - darkly