```{python}
# Definer prosjekt og dataset
PROJECT = "pia-prod-85b2"
DATASET = "pia_bigquery_sink_v1_dataset_prod"
```

```{python}
# Hent data om IA-saker
import pandas as pd
from src.utils.dataloader import last_inn_data_statistikk
data_statistikk = last_inn_data_statistikk(
    project=PROJECT,
    dataset=DATASET,
    adm_enheter=pd.read_csv("data/administrative_enheter.csv", dtype=str),
    resultatområde=RESULTATOMRÅDE,
)
```

```{python}
# Hent data om samarbeid
from src.utils.dataloader import last_inn_samarbeid
data_samarbeid = last_inn_samarbeid(
    project=PROJECT,
    dataset=DATASET,
    data_statistikk=data_statistikk,
    resultatområde=RESULTATOMRÅDE,
)
```

```{python}
# Last inn data om samarbeidsplaner
from src.utils.dataloader import last_inn_data_samarbeidsplan
data_samarbeidsplan = last_inn_data_samarbeidsplan(
    project=PROJECT,
    dataset=DATASET,
    data_samarbeid=data_samarbeid,
    resultatområde=RESULTATOMRÅDE,
)
```

{{< include includes/under_arbeid_callout.qmd >}}



# Innhold i samarbeidsplaner

Denne datafortellingen gir en oversikt over samarbeidsplaner. Det blir ikke inkludert samarbeid som ikke har en tilknyttet samarbeidsplan i visninger nedenfor.

::: {.panel-tabset}

## Alle samarbeid

```{python}
# Filtrerer samarbeidsplaner etter status Aktiv, Avbrutt og Fullført
from src.utils.datahandler import grupper_samarbeid_etter_samarbeid_status
samarbeid_status = ["AKTIV", "AVBRUTT", "FULLFØRT"]
antall_planer_med_innhold, antall_planer_totalt, inkluderte_undertemaer = grupper_samarbeid_etter_samarbeid_status(data_samarbeidsplan, samarbeid_status)
```

For alle samarbeid med en plan er det `{python} antall_planer_med_innhold` av `{python} antall_planer_totalt` planer har noe innhold.

```{python}
# Plotter innhold i samarbeidsplaner etter status på innhold
from src.plots.samarbeidsplaner import plot_samarbeidsplaner_etter_status
plot_samarbeidsplaner_etter_status(data=inkluderte_undertemaer)
```

## Aktive

```{python}
# Filtrerer samarbeidsplaner etter status Aktiv
samarbeid_status = ["AKTIV"]
antall_planer_med_innhold, antall_planer_totalt, inkluderte_undertemaer = grupper_samarbeid_etter_samarbeid_status(data_samarbeidsplan, samarbeid_status)
```

For aktive samarbeid med en plan er det `{python} antall_planer_med_innhold` av `{python} antall_planer_totalt` planer har noe innhold.


```{python}
# Plotter innhold i samarbeidsplaner etter status på innhold
plot_samarbeidsplaner_etter_status(data=inkluderte_undertemaer)
```


## Avbrutte

```{python}
# Filtrerer samarbeidsplaner etter status Avbrutt
samarbeid_status = ["AVBRUTT"]
antall_planer_med_innhold, antall_planer_totalt, inkluderte_undertemaer = grupper_samarbeid_etter_samarbeid_status(data_samarbeidsplan, samarbeid_status)
```

For avbrutte samarbeid med en plan er det `{python} antall_planer_med_innhold` av `{python} antall_planer_totalt` planer har noe innhold.

```{python}
# Plotter innhold i samarbeidsplaner etter status på innhold
plot_samarbeidsplaner_etter_status(data=inkluderte_undertemaer)
```

## Fullførte

```{python}
# Filtrerer samarbeidsplaner etter status Fullført
samarbeid_status = ["FULLFØRT"]
antall_planer_med_innhold, antall_planer_totalt, inkluderte_undertemaer = grupper_samarbeid_etter_samarbeid_status(data_samarbeidsplan, samarbeid_status)
```

For fullførte samarbeid med en plan er det `{python} antall_planer_med_innhold` av `{python} antall_planer_totalt` planer har noe innhold.


```{python}
# Plotter innhold i samarbeidsplaner etter status på innhold
plot_samarbeidsplaner_etter_status(data=inkluderte_undertemaer)
```


:::


```{python}
# Utforsk data






# ['id', 'samarbeidId', 'endret', 'tidsstempel', 'saksnummer','resultatomrade', 'sektor']
# plan Id = UUID string
# samarbeidId = Int
# endret = datetime
# tidsstempel = datetime # sendt til bigquery
# saksnummer = usikker på når dette er relevant for sjekk av innhold
# resultatområde = Resultatområde
# TODO: drop nan resultatområde
# sektor = sektor
# TODO: drop <NA> sektor



# Da rader er lik undertemaer i plan, så kan vi telle antall rader for å finne antall innhold i plan hvor plan_id er unik.
# Bør være samme som group by plan_id og så telle sum








# TODO: Bør legge til status på samarbeid?
# print(len(data_samarbeidsplan.groupby("plan_id")))

# TODO: må sjekke innhold i plan også
# Det betyr at vi må hente innhold og kanskje knytte det til samarbeidsplanen via tematabellen?






```




<!-- 
#TODO:
- Fra gjennomført evaluering til gjennomført samarbeid
- Filtrer inn-data på sektor
- Dropdown: Næring + Bransje
- Legend: multi plots, antall arbeidsforhold?

todo
# Plan

## Varighet innhold
Hvor lang varighet settes det for undertemaer / innhold i plan?
Fordel dette på sektor / Næring / Bransje (geografi skjer på resultatområde)

## Innhold i plan
Hvilke innhold er oftest med i plan?
Fordel dette på sektor / Næring / Bransje (geografi skjer på resultatområde)

## Endring av plan
Skjer det endringer på statuser på innhold en plan?
Fordel dette på sektor / Næring / Bransje (geografi skjer på resultatområde) ?

## Fullføring / Avbryting av plan
Skjer dette lenge før eller etter fristen?
Se datakvalitet fordeling før og etter antall dager.
Fordel dette på sektor / Næring / Bransje (geografi skjer på resultatområde)


# SF
## Aktiviteter på innhold
Hvor mange aktiviteter settes det i salesforce per type innhold?
Fordel dette på sektor / Næring / Bransje (geografi skjer på resultatområde) -->



<!-- Samme som resultatområder: -->

<!-- Include datafortelling_samarbeidsplan -->

<!-- Kun for Norge: -->


