---
title: "Fia datakvalitet"
subtitle: Statistikk som viser datakvalitet i Fia - Fagsystemet for oppfølging av IA-oppdraget i NAV.
title-block-banner: true
title-block-banner-color: white
date: now
date-format: "DD.MM.YYYY HH:mm:ss z"
published-title: "Oppdatert"
author: Team Pia
author-title: "Eier"
execute:
    echo: false
    warning: false
format:
    html:
        toc: true
        toc-title: Indeks
        page-layout: full
        embed-resources: true
jupyter: python3
---

Ansvarlig team er [Team Pia](https://teamkatalog.nav.no/team/b347ac99-c382-4e5a-a1dd-532e91110e2a).
Kontakt oss på [slack](https://nav-it.slack.com/archives/C02DL347ZT2) eller på e-post `pia@nav.no`.

Kildekoden finnes på [GitHub](https://github.com/navikt/fia-datafortelling).

<span style="color:red;">
NB! Dette er ikke offisiell statistikk og må ikke deles utenfor NAV.
</span>

```{python}
import os

from code.datahandler import (
    load_data,
    load_data_deduplicate,
    preprocess_data_statistikk,
    split_data_statistikk,
    preprocess_data_status,
    preprocess_data_leveranse,
    hent_leveranse_sistestatus,
    beregn_intervall_tid_siden_siste_endring,
    explode_ikke_aktuell_begrunnelse,
)
from code.plots import (
    urørt_saker_over_tid,
    antall_leveranser_per_sak,
)
from code.plots_statistikk import (
    saker_per_status_over_tid,
    dager_mellom_statusendringer,
    median_og_gjennomsnitt_av_tid_mellom_statusendringer,
    fullført_per_måned,
    antall_saker_per_eier,
    antall_brukere_per_måned,
    antall_brukere_per_fylke,
    antall_brukere_per_fylke_og_nav_enhet,
    andel_superbrukere,
    andel_statusendringer_gjort_av_superbrukere,
)
from code.plots_leveranse import (
    forskjell_frist_fullfort,
    andel_leveranseregistreringer_gjort_av_superbrukere,
)


PROJECT = os.environ['GCP_PROJECT']
DATASET = os.environ['DATASET']
raw_data_statistikk = load_data_deduplicate(PROJECT, DATASET, "ia-sak-statistikk-v1")
raw_data_leveranse = load_data(PROJECT, DATASET, "ia-sak-leveranse-v1")

data_statistikk = preprocess_data_statistikk(raw_data_statistikk)
data_status, data_eierskap = split_data_statistikk(data_statistikk)
data_status = preprocess_data_status(data_status)
data_leveranse = preprocess_data_leveranse(raw_data_leveranse)
data_leveranse_sistestatus = hent_leveranse_sistestatus(data_leveranse)
ikke_aktuell = explode_ikke_aktuell_begrunnelse(data_status)
```


## Antall saker per status over tid
```{python}
saker_per_status_over_tid(data_status)
```

## Tid mellom statusendringer
Grafene under viser hvor lenge saker står i en status (før de går over i en annen).
Vi har valgt å dele intervaller på en ujevn måte for å kunne se om endringer tar kort eller lang tid.
Hver bar viser gjeldende periode (fra og med, til).

```{python}
data_status = beregn_intervall_tid_siden_siste_endring(data_status)
```

::: {.panel-tabset}

## Fra Vurderes
::: {.panel-tabset}
## Til Kontaktes
```{python}
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VURDERES") & (data_status.status=="KONTAKTES")]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VURDERES") & (data_status.status=="KONTAKTES")]
)
```
## Til Ikke aktuell
```{python}
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VURDERES") & (data_status.status=="IKKE_AKTUELL")]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VURDERES") & (data_status.status=="IKKE_AKTUELL")]
)
```
## Til Slettet
```{python}
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VURDERES") & (data_status.status=="SLETTET")]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VURDERES") & (data_status.status=="SLETTET")]
)
```
## Til Kontaktes, Ikke aktuell eller Slettet
```{python}
dager_mellom_statusendringer(
    data_status[data_status.forrige_status=="VURDERES"]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[data_status.forrige_status=="VURDERES"]
)
```
:::

## Fra Kontaktes
::: {.panel-tabset}
## Til Kartlegges
```{python}
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="KONTAKTES") & (data_status.status=="KARTLEGGES")]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="KONTAKTES") & (data_status.status=="KARTLEGGES")]
)
```
## Til Ikke aktuell
```{python}
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="KONTAKTES") & (data_status.status=="IKKE_AKTUELL")]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="KONTAKTES") & (data_status.status=="IKKE_AKTUELL")]
)
```
## Til Kartlegges eller Ikke aktuell
```{python}
dager_mellom_statusendringer(
    data_status[data_status.forrige_status=="KONTAKTES"]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[data_status.forrige_status=="KONTAKTES"]
)
```
:::

## Fra Kartlegges
::: {.panel-tabset}
## Til Vi bistår
```{python}
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="KARTLEGGES") & (data_status.status=="VI_BISTÅR")]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="KARTLEGGES") & (data_status.status=="VI_BISTÅR")]
)
```
## Til Ikke aktuell
```{python}
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="KARTLEGGES") & (data_status.status=="IKKE_AKTUELL")]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="KARTLEGGES") & (data_status.status=="IKKE_AKTUELL")]
)
```
## Til Vi bistår eller Ikke aktuell
```{python}
dager_mellom_statusendringer(
    data_status[data_status.forrige_status=="KARTLEGGES"]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[data_status.forrige_status=="KARTLEGGES"]
)
```
:::

## Fra Vi bistår
::: {.panel-tabset}
## Til Fullført
```{python}
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VI_BISTÅR") & (data_status.status=="FULLFØRT")]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VI_BISTÅR") & (data_status.status=="FULLFØRT")]
)
```
## Til Ikke aktuell
```{python}
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VI_BISTÅR") & (data_status.status=="IKKE_AKTUELL")]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VI_BISTÅR") & (data_status.status=="IKKE_AKTUELL")]
)
```
## Til Fullført eller Ikke aktuell
```{python}
dager_mellom_statusendringer(
    data_status[data_status.forrige_status=="VI_BISTÅR"]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[data_status.forrige_status=="VI_BISTÅR"]
)
```
:::
:::


## Antal saker som ligger urørt i Fia
Grafene under viser, per beregningsdato, hvor mange saker som ikke var oppdatert i Fia i 90 dager.
En oppdatering er at noen har tatt eierskap til en sak, en endring av status eller en leveranse som er lagt til eller satt til levert.
Hvis en statusendring blir angret (ved bruk av tilbake-knappen) eller en leveranse blir slettet, telles ikke dette som oppdatering.

```{python}
urørt_saker_over_tid(data_status, data_eierskap, data_leveranse, antall_dager=90)
```


## Antall saker per eier
Vise antall saker i status "Vi bistår" eller "Fullført" per eier. Gjelder bare siste eier per sak.

```{python}
antall_saker_per_eier(data_status)
```


## Antall fullførte saker per måned
```{python}
fullført_per_måned(data_status)
```


## Forskjellen mellom frist og fullført dato
```{python}
forskjell_frist_fullfort(data_leveranse_sistestatus)
```


## Antall moduler per sak
Grafen nedenfor viser moduler per sak, i.e., hvor mange moduler som leveres til virksomheter under bistand.
Her gjelder alle saker som har leveranser registert eller kunne ha hatt det, i.e., saker fullført etter det ble mulig å registrere leveranser (mars 2023), og saker i bistand nå.

```{python}
antall_leveranser_per_sak(data_status, data_leveranse_sistestatus)
```


## Antall brukere
Antall unike brukere som har gjort noe som fører til en statusendring.

::: {.panel-tabset}
## Per måned
```{python}
antall_brukere_per_måned(data_statistikk)
```

## Per fylke
En bruker kan telles i flere fylker.
```{python}
antall_brukere_per_fylke(data_statistikk)
```

## Per fylke og NAV-enhet
En bruker kan telles i flere fylker, men bare i den siste NAV-enheten bruker er registrert med.
NAV-enhet begynte å bli registrert i databasen 2023-05-05.
```{python}
antall_brukere_per_fylke_og_nav_enhet(data_statistikk)
```
:::


## Brukerrolle
::: {.panel-tabset}
## Andel superbrukere
```{python}
andel_superbrukere(data_statistikk)
```
## Andel statusendringer
Andel statusendringer gjort av superbrukere.
```{python}
andel_statusendringer_gjort_av_superbrukere(data_statistikk)
```
## Andel leveranser
Andel leveranser satt til fullført av superbrukere.
```{python}
andel_leveranseregistreringer_gjort_av_superbrukere(data_leveranse)
```
:::
