---
title: "Fia datafortelling for {{< env FYLKESNAVN >}}"
subtitle: Statistikk som viser bruk av Fia - Fagsystemet for oppfølging av IA-oppdraget i NAV.
title-block-banner: true
title-block-banner-color: white
date: now
date-format: "DD.MM.YYYY HH:mm:ss z"
published-title: "Oppdatert"
author: Team Pia
author-title: "Eier"
execute:
    echo: false
    warning: false
    daemon: false
format:
    html:
        toc: true
        toc-title: Indeks
        page-layout: full
        embed-resources: true
jupyter: python3
---

**Vi ønsker tilbakemelding fra dere! Meld inn forslag til datafortellingen i [Porten](https://jira.adeo.no/plugins/servlet/desk/portal/541/create/4362).**

Ansvarlig team er [Team Pia](https://teamkatalog.nav.no/team/b347ac99-c382-4e5a-a1dd-532e91110e2a).
Kontakt oss på [slack](https://nav-it.slack.com/archives/C02DL347ZT2) eller på e-post `pia@nav.no`.

Kildekoden finnes på [GitHub](https://github.com/navikt/fia-datafortelling).

<span style="color:red;">
NB! Dette er ikke offisiell statistikk og må ikke deles utenfor NAV.
</span>

```{python}
%load_ext autoreload
%autoreload 2

import os

from code.datahandler import (
    load_data,
    load_data_deduplicate,
    preprocess_data_statistikk,
    split_data_statistikk,
    preprocess_data_status,
    preprocess_data_leveranse,
    hent_leveranse_sistestatus,
    explode_ikke_aktuell_begrunnelse,
    filtrer_bort_saker_på_avsluttet_tidspunkt,
)
from code.plots import (
    dager_siden_siste_oppdatering,
    andel_fullforte_saker_med_leveranse_per_måned,
)
from code.plots_statistikk import (
    statusflyt,
    gjennomstrømmingstall,
    saker_per_status_per_måned,
    antall_saker_per_status,
    aktive_saker_per_fylke,
    virksomhetsprofil,
)
from code.plots_leveranse import (
    antall_leveranser_per_tjeneste,
    antall_leveranser_per_modul,
    begrunnelse_ikke_aktuell,
    leveranse_per_maaned,
    leveranse_tjeneste_per_maaned,
)
from code.helper import (
    ikke_aktuell_begrunnelse_sortering,
    iatjeneste_og_status_sortering,
)
from code.konstanter import (
    ikkeaktuell_hovedgrunn,
    fylker,
)


PROJECT = os.environ['GCP_PROJECT']
DATASET = os.environ['DATASET']
raw_data_statistikk = load_data_deduplicate(PROJECT, DATASET, "ia-sak-statistikk-v1")
raw_data_leveranse = load_data(PROJECT, DATASET, "ia-sak-leveranse-v1")

fylkesnavn = os.environ['FYLKESNAVN']
for nr, navn in fylker.items():
    if navn == fylkesnavn:
        fylkesnr = nr

raw_data_leveranse = raw_data_leveranse.merge(
    raw_data_statistikk[["saksnummer", "fylkesnummer", "bransjeprogram"]], 
    how='left', 
    on='saksnummer',
)

data_statistikk = preprocess_data_statistikk(raw_data_statistikk)
data_status, data_eierskap = split_data_statistikk(data_statistikk)
data_status = preprocess_data_status(data_status)
data_leveranse = preprocess_data_leveranse(raw_data_leveranse)
data_leveranse_sistestatus = hent_leveranse_sistestatus(data_leveranse)
ikke_aktuell = explode_ikke_aktuell_begrunnelse(data_status)

data_statistikk_fylke = data_statistikk[data_statistikk.fylkesnummer == fylkesnr]
data_status_fylke = data_status[data_status.fylkesnummer == fylkesnr]
data_eierskap_fylke = data_eierskap[data_eierskap.fylkesnummer == fylkesnr]
data_leveranse_fylke = data_leveranse[data_leveranse.fylkesnummer == fylkesnr]
data_leveranse_sistestatus_fylke = data_leveranse_sistestatus[data_leveranse_sistestatus.fylkesnummer == fylkesnr]
ikke_aktuell_fylke = ikke_aktuell[ikke_aktuell.fylkesnummer == fylkesnr]
```


## Antall saker per status

::: {.panel-tabset}
# Nåsituasjon
```{python}
antall_saker_per_status(data_status_fylke[data_status.aktiv_sak])
```

# Historikk
Vi filtrerer bort saker som ble satt til "Fullført", "Ikke aktuell", eller "Slettet" for over ett år siden.
```{python}
saker_per_status_per_måned(data_status_fylke)
```

# Gjennomstrømmingstall
Viser hvor mange saker som går inn og ut av status **Vi bistår**.
Fra status Vi bistår er det mulig å skifte til enten Fullført eller Ikke aktuell.
```{python}
gjennomstrømmingstall(data_status_fylke)
```
:::

{{< include includes/sak-forklaring.qmd >}}
{{< include includes/saksstatus-forklaring.qmd >}}

## Dager siden siste oppdatering i Fia
Grafene under viser hvor mange dager det har gått siden siste oppdatering per sak i Fia.
En oppdatering er at noen har tatt eierskap til en sak, en endring av status eller en leveranse som er lagt til eller satt til levert.
Hvis en statusendring blir angret (ved bruk av tilbake-knappen) eller en leveranse blir slettet, telles ikke dette som oppdatering.
Vi viser disse tallene fordelt på status, siden statusene kan ha ulik varighet.
Grafene gir en indikasjon på hvor mange saker som ligger urørt i Fia.

::: {.panel-tabset}
## Alle aktive saker
```{python}
dager_siden_siste_oppdatering(data_status_fylke, data_eierskap_fylke, data_leveranse_fylke)
```
## Vurderes
```{python}
dager_siden_siste_oppdatering(
    data_status_fylke[data_status_fylke.siste_status=="VURDERES"],
    data_eierskap_fylke,
    data_leveranse_fylke
)
```
## Kontaktes
```{python}
dager_siden_siste_oppdatering(
    data_status_fylke[data_status_fylke.siste_status=="KONTAKTES"],
    data_eierskap_fylke,
    data_leveranse_fylke
)
```
## Kartlegges
```{python}
dager_siden_siste_oppdatering(
    data_status_fylke[data_status_fylke.siste_status=="KARTLEGGES"],
    data_eierskap_fylke,
    data_leveranse_fylke
)
```
## Vi bistår
```{python}
dager_siden_siste_oppdatering(
    data_status_fylke[data_status_fylke.siste_status=="VI_BISTÅR"],
    data_eierskap_fylke,
    data_leveranse_fylke
)
```
:::


## Leveranser
Når en sak har status "Vi bistår" kan eier av saken registrere hvilke IA-tjenester/moduler som er under arbeid eller levert.
En sak kan ikke gå videre til status "Fullført" før alle registrerte leveranser er satt som levert eller er slettet.
Slettet leveranser vises ikke i grafene under.


#### Antall fullførte leveranser
PS: En sak kan ha flere leveranser.

::: {.panel-tabset}
# Totalt
```{python}
leveranse_per_maaned(data_leveranse_sistestatus_fylke)
```
# Per tjeneste
```{python}
leveranse_tjeneste_per_maaned(data_leveranse_sistestatus_fylke)
```
:::


#### Antall saker som har leveranser registrert med IA-tjenester
```{python}
# Filtrerer bort saker avsluttet for over ett år siden
data_status_fylke_siste_år = filtrer_bort_saker_på_avsluttet_tidspunkt(data_status_fylke)
data_leveranse_sistestatus_fylke_siste_år = data_leveranse_sistestatus_fylke[
    data_leveranse_sistestatus_fylke.saksnummer.isin(data_status_fylke_siste_år.saksnummer.unique())
]

alle_iatjenester_og_status = iatjeneste_og_status_sortering(data_leveranse_sistestatus)
```

::: {.panel-tabset}
# Alle virksomheter
PS: Én sak kan ha leveranser i flere tjenester.
```{python}
antall_leveranser_per_tjeneste(data_leveranse_sistestatus_fylke_siste_år, alle_iatjenester_og_status)
```

# Per bransjeprogram
PS: Én sak kan ha leveranser i flere tjenester.

::: {.panel-tabset}
# Barnehager
```{python}
data = data_leveranse_sistestatus_fylke_siste_år[
    data_leveranse_sistestatus_fylke_siste_år.bransjeprogram=="BARNEHAGER"
]
if data.empty:
    print("Det finnes ikke registerte leveranser i denne bransjen")
else:
    antall_leveranser_per_tjeneste(data, alle_iatjenester_og_status).show()
```

# Sykehjem
```{python}
data = data_leveranse_sistestatus_fylke_siste_år[
    data_leveranse_sistestatus_fylke_siste_år.bransjeprogram=="SYKEHJEM"
]
if data.empty:
    print("Det finnes ikke registerte leveranser i denne bransjen")
else:
    antall_leveranser_per_tjeneste(data, alle_iatjenester_og_status).show()
```

# Sykehus
```{python}
data = data_leveranse_sistestatus_fylke_siste_år[
    data_leveranse_sistestatus_fylke_siste_år.bransjeprogram=="SYKEHUS"
]
if data.empty:
    print("Det finnes ikke registerte leveranser i denne bransjen")
else:
    antall_leveranser_per_tjeneste(data, alle_iatjenester_og_status).show()
```

# Næringsmiddelindustri
```{python}
data = data_leveranse_sistestatus_fylke_siste_år[
    data_leveranse_sistestatus_fylke_siste_år.bransjeprogram=="NÆRINGSMIDDELINDUSTRI"
]
if data.empty:
    print("Det finnes ikke registerte leveranser i denne bransjen")
else:
    antall_leveranser_per_tjeneste(data, alle_iatjenester_og_status).show()
```

# Bygg og anlegg
```{python}
data = data_leveranse_sistestatus_fylke_siste_år[
    data_leveranse_sistestatus_fylke_siste_år.bransjeprogram.isin(["BYGG", "ANLEGG"])
]
if data.empty:
    print("Det finnes ikke registerte leveranser i denne bransjen")
else:
    antall_leveranser_per_tjeneste(data, alle_iatjenester_og_status).show()
```

# Transport
```{python}
data = data_leveranse_sistestatus_fylke_siste_år[
    data_leveranse_sistestatus_fylke_siste_år.bransjeprogram=="TRANSPORT"
]
if data.empty:
    print("Det finnes ikke registerte leveranser i denne bransjen")
else:
    antall_leveranser_per_tjeneste(data, alle_iatjenester_og_status).show()
```
:::
:::

{{< include includes/leveransestatus-forklaring.qmd >}}


#### Andel fullførte saker med leveranse registrert
PS: Manglende verdier kan oppstå når det ikke er fullført noen saker den måneden.
```{python}
andel_fullforte_saker_med_leveranse_per_måned(data_status_fylke, data_leveranse_fylke)
```


## Virksomhetsprofil
Her vises profilen til virksomheter som er registrert i Fia.
Grafene viser antall saker per antall arbeidsforhold, sykefravæarsprosent, sektor, bransjeprogram og de 10 vanligste hovednæringer.
Alle tallene er basert på informasjon vi hadde da de relevante statusendringene skjedde.

PS: En virksomhet kan bare ha én aktiv sak om gangen, men flere saker over tid.

Du finner flere detaljer om statistikk i [Brukerveiledning for Fia på Navet](https://navno.sharepoint.com/sites/intranett-produktomrader-og-prosjekter/SitePages/FIA-brukerveiledning.aspx).

::: {.panel-tabset}

## Før bistand
Saker med nåværende status "Vurderes", "Kontaktes" eller "Kartlegges".\
```{python}
data_input = data_status_fylke[data_status_fylke.siste_status.isin(["VURDERES", "KONTAKTES", "KARTLEGGES"])]
virksomhetsprofil(data_input)
```

## I bistand
Saker med nåværende status "Vi bistår".\
```{python}
data_input = data_status_fylke[data_status_fylke.siste_status=="VI_BISTÅR"]
virksomhetsprofil(data_input)
```

## Ikke aktuell
Saker som ble satt til "Ikke aktuell" i de siste 365 dagene.\

```{python}
data_input = data_status_fylke[data_status_fylke.siste_status=="IKKE_AKTUELL"].drop_duplicates("saksnummer", keep="last")
data_input = filtrer_bort_saker_på_avsluttet_tidspunkt(data_input)
virksomhetsprofil(data_input)
```

## Fullført
Saker som ble satt til "Fullført" i de siste 365 dagene.\

```{python}
data_input = data_status_fylke[data_status_fylke.siste_status=="FULLFØRT"].drop_duplicates("saksnummer", keep="last")
data_input = filtrer_bort_saker_på_avsluttet_tidspunkt(data_input)
virksomhetsprofil(data_input)
```

:::


## Begrunnelse på ikke aktuell
Her vises andel og antall saker per begrunnelse på ikke aktuell.
Gjelder bare saker med nåværende status "Ikke aktuell", og ikke de sakene som ble angret (ved bruk av tilbake-knappen).
Når en sak settes til "Ikke aktuell" må eieren velge minst en begrunnelse, så en sak kan telles i flere begrunnelser,
og derfor kan andelssummen være større enn 100%.

```{python}
begrunnelse_sortering = ikke_aktuell_begrunnelse_sortering(ikke_aktuell)
data_input = filtrer_bort_saker_på_avsluttet_tidspunkt(
    ikke_aktuell_fylke[ikke_aktuell_fylke.ikkeAktuelBegrunnelse.isin(ikkeaktuell_hovedgrunn.keys())]
)
begrunnelse_ikke_aktuell(data_input, begrunnelse_sortering)
```

{{< include includes/ikke-aktuell-forklaring.qmd >}}

Du finner flere detaljer om statistikk i [Brukerveiledning for Fia på Navet](https://navno.sharepoint.com/sites/intranett-produktomrader-og-prosjekter/SitePages/FIA-brukerveiledning.aspx).