---
title: "Fia datafortelling for {{< env RESULTATOMRADE >}}"
subtitle: Statistikk som viser bruk av Fia - Fagsystemet for oppfølging av IA-oppdraget i NAV.
title-block-banner: true
title-block-banner-color: white
date: now
date-format: "DD.MM.YYYY HH:mm:ss z"
published-title: "Oppdatert"
author: Team Pia
author-title: "Eier"
execute:
    echo: false
    warning: false
    daemon: false
format:
    html:
        toc: true
        toc-title: Indeks
        page-layout: full
        embed-resources: true
jupyter: python3
---

**Vi ønsker tilbakemelding fra dere! Meld inn forslag til datafortellingen i [Porten](https://jira.adeo.no/plugins/servlet/desk/portal/541/create/4362).**

Ansvarlig team er [Team Pia](https://teamkatalog.nav.no/team/b347ac99-c382-4e5a-a1dd-532e91110e2a).
Kontakt oss på [slack](https://nav-it.slack.com/archives/C02DL347ZT2) eller på e-post `pia@nav.no`.

Kildekoden finnes på [GitHub](https://github.com/navikt/fia-datafortelling).

<span style="color:red;">
NB! Dette er ikke offisiell statistikk og må ikke deles utenfor NAV.
</span>

```{python}
%load_ext autoreload
%autoreload 2

import os

from datahandler import (
    load_data_deduplicate,
    preprocess_data_statistikk,
    split_data_statistikk,
    preprocess_data_status,
    preprocess_data_leveranse,
    preprocess_data_samarbeid,
    hent_leveranse_sistestatus,
    explode_ikke_aktuell_begrunnelse,
    filtrer_bort_saker_på_avsluttet_tidspunkt,
    legg_til_resultatområde,
)
from plots_statistikk import (
    statusflyt,
    gjennomstrømmingstall,
    saker_per_status_per_måned,
    antall_saker_per_status,
    virksomhetsprofil,
)
from plots_leveranse import (
    antall_leveranser_per_tjeneste,
    begrunnelse_ikke_aktuell,
    leveranse_per_maaned,
    leveranse_tjeneste_per_maaned,
)
from plots_samarbeid import (
    plot_antall_saker_per_antall_samarbeid,
    trakt_antall_samarbeid,
)
from helper import (
    ikke_aktuell_begrunnelse_sortering,
    iatjeneste_og_status_sortering,
)
from konstanter import (
    ikkeaktuell_hovedgrunn,
    resultatområder,
)


PROJECT = os.environ['GCP_PROJECT']
DATASET = os.environ['DATASET']

navn = os.environ['RESULTATOMRADE']
if navn in resultatområder.values():
    resultatområde = navn
else:
    raise ValueError(f"Resultatområde '{navn}' er ikke gyldig.")

# Henter data om hendelser og statusendringer
# med statistikk: sykefravær, bransje, antall ansatte, osv.
raw_data_statistikk = load_data_deduplicate(PROJECT, DATASET, "ia-sak-statistikk-v1", "endretAvHendelseId")
data_statistikk = preprocess_data_statistikk(raw_data_statistikk)
data_statistikk_resultatområde = data_statistikk[data_statistikk.resultatomrade == resultatområde]
data_status_resultatområde, data_eierskap_resultatområde, _ = split_data_statistikk(data_statistikk_resultatområde)
data_status_resultatområde = preprocess_data_status(data_status_resultatområde)
ikke_aktuell_resultatområde = explode_ikke_aktuell_begrunnelse(data_status_resultatområde)

# Henter data om IA-tjenester
raw_data_leveranse = load_data_deduplicate(PROJECT, DATASET, "ia-sak-leveranse-v1", "id, status")
raw_data_leveranse = legg_til_resultatområde(raw_data_leveranse, data_statistikk)
raw_data_leveranse_resultatområde = raw_data_leveranse[raw_data_leveranse.resultatomrade == resultatområde]
data_leveranse_resultatområde = preprocess_data_leveranse(raw_data_leveranse_resultatområde)
data_leveranse_sistestatus_resultatområde = hent_leveranse_sistestatus(data_leveranse_resultatområde)

# Henter data om samarbeid/prosess
raw_data_samarbeid = load_data_deduplicate(PROJECT, DATASET, "samarbeid-bigquery-v1", distinct_colunms="id")
raw_data_samarbeid = legg_til_resultatområde(raw_data_samarbeid, data_statistikk)
raw_data_samarbeid_resultatområde = raw_data_samarbeid[raw_data_samarbeid.resultatomrade == resultatområde]
data_samarbeid_resultatområde = preprocess_data_samarbeid(raw_data_samarbeid_resultatområde, data_statistikk_resultatområde)

# Henter data om behovsvurdering
data_behovsvurdering = load_data_deduplicate(PROJECT, DATASET, "behovsvurdering-bigquery-v1", distinct_colunms="id")
# behovsvurderingstabellen har ikke saksnummer enda, så vi må legge det til
data_behovsvurdering = data_behovsvurdering.merge(
    raw_data_samarbeid[["id", "saksnummer"]].rename({"id": "samarbeidId"}, axis = 1),
    how="left", on="samarbeidId",
)
data_behovsvurdering = legg_til_resultatområde(data_behovsvurdering, data_statistikk)
data_behovsvurdering_resultatområde = data_behovsvurdering[data_behovsvurdering.resultatomrade == resultatområde]

# Henter data om samarbeidsplan
data_samarbeidsplan = load_data_deduplicate(PROJECT, DATASET, "samarbeidsplan-bigquery-v1", distinct_colunms="id")
# samarbeidsplantabellen har ikke saksnummer enda, så vi må legge det til
data_samarbeidsplan = data_samarbeidsplan.merge(
    raw_data_samarbeid[["id", "saksnummer"]].rename({"id": "samarbeidId"}, axis = 1),
    how="left", on="samarbeidId",
)
data_samarbeidsplan = legg_til_resultatområde(data_samarbeidsplan, data_statistikk)
data_samarbeidsplan_resultatområde = data_samarbeidsplan[data_samarbeidsplan.resultatomrade == resultatområde]
```


## Antall samarbeid
```{python}
trakt_antall_samarbeid(
    data_samarbeid_resultatområde,
    data_behovsvurdering_resultatområde,
    data_samarbeidsplan_resultatområde,
)
```


## Antall samarbeid per virksomhet
::: {.panel-tabset}
# Antall
```{python}
plot_antall_saker_per_antall_samarbeid(data_samarbeid_resultatområde)
```

# Andel
```{python}
plot_antall_saker_per_antall_samarbeid(data_samarbeid_resultatområde, normalisert=True)
```
:::


## Antall saker per status

::: {.panel-tabset}
# Nåsituasjon
```{python}
antall_saker_per_status(data_status_resultatområde[data_status_resultatområde.aktiv_sak])
```

# Historikk
Vi filtrerer bort saker som ble satt til "Fullført", "Ikke aktuell", eller "Slettet" for over ett år siden.
```{python}
saker_per_status_per_måned(data_status_resultatområde)
```

# Gjennomstrømmingstall
Viser hvor mange saker som går inn og ut av status **Vi bistår**.
Fra status Vi bistår er det mulig å skifte til enten Fullført eller Ikke aktuell.
```{python}
gjennomstrømmingstall(data_status_resultatområde)
```
:::

{{< include includes/sak-forklaring.qmd >}}
{{< include includes/saksstatus-forklaring.qmd >}}


## Leveranser

```{python}
lenke_til_ia_tjenester = f"ia_tjenester_per_resultatområde_{navn.replace(' ', '_')}.html"
```

IA-tjenester er faset ut og erstattet med samarbeidsplanen i Fia.
Du kan finne de gamle dataene om IA-tjenester i ditt fylke [her](`{python} lenke_til_ia_tjenester`).
Info om samarbeidsplan kommer senere.

## Virksomhetsprofil
Her vises profilen til virksomheter som er registrert i Fia.
Grafene viser antall saker per antall arbeidsforhold, sykefravæarsprosent, sektor, bransjeprogram og de 10 vanligste hovednæringer.
Alle tallene er basert på informasjon vi hadde da de relevante statusendringene skjedde.

PS: En virksomhet kan bare ha én aktiv sak om gangen, men flere saker over tid.

Du finner flere detaljer om statistikk i [Brukerveiledning for Fia på Navet](https://navno.sharepoint.com/sites/intranett-produktomrader-og-prosjekter/SitePages/FIA-brukerveiledning.aspx).

::: {.panel-tabset}

## Før bistand
Saker med nåværende status "Vurderes", "Kontaktes" eller "Kartlegges".\
```{python}
data_input = data_status_resultatområde[data_status_resultatområde.siste_status.isin(["VURDERES", "KONTAKTES", "KARTLEGGES"])]
virksomhetsprofil(data_input)
```

## I bistand
Saker med nåværende status "Vi bistår".\
```{python}
data_input = data_status_resultatområde[data_status_resultatområde.siste_status=="VI_BISTÅR"]
virksomhetsprofil(data_input)
```

## Ikke aktuell
Saker som ble satt til "Ikke aktuell" i de siste 365 dagene.\

```{python}
data_input = data_status_resultatområde[data_status_resultatområde.siste_status=="IKKE_AKTUELL"].drop_duplicates("saksnummer", keep="last")
data_input = filtrer_bort_saker_på_avsluttet_tidspunkt(data_input)
virksomhetsprofil(data_input)
```

## Fullført
Saker som ble satt til "Fullført" i de siste 365 dagene.\

```{python}
data_input = data_status_resultatområde[data_status_resultatområde.siste_status=="FULLFØRT"].drop_duplicates("saksnummer", keep="last")
data_input = filtrer_bort_saker_på_avsluttet_tidspunkt(data_input)
virksomhetsprofil(data_input)
```

:::


## Begrunnelse på ikke aktuell
Her vises andel og antall saker per begrunnelse på ikke aktuell.
Gjelder bare saker med nåværende status "Ikke aktuell", og ikke de sakene som ble angret (ved bruk av tilbake-knappen).
Når en sak settes til "Ikke aktuell" må eieren velge minst en begrunnelse, så en sak kan telles i flere begrunnelser,
og derfor kan andelssummen være større enn 100%.

```{python}
begrunnelse_sortering = ikke_aktuell_begrunnelse_sortering(ikke_aktuell_resultatområde)
data_input = filtrer_bort_saker_på_avsluttet_tidspunkt(
    ikke_aktuell_resultatområde[ikke_aktuell_resultatområde.ikkeAktuelBegrunnelse.isin(ikkeaktuell_hovedgrunn.keys())]
)
begrunnelse_ikke_aktuell(data_input, begrunnelse_sortering)
```

{{< include includes/ikke-aktuell-forklaring.qmd >}}

Du finner flere detaljer om statistikk i [Brukerveiledning for Fia på Navet](https://navno.sharepoint.com/sites/intranett-produktomrader-og-prosjekter/SitePages/FIA-brukerveiledning.aspx).
