```{python}
%load_ext autoreload
%autoreload 2

import os
import pandas as pd

from src.utils.datahandler import (
    load_data_deduplicate,
    preprocess_data_statistikk,
    split_data_statistikk,
    preprocess_data_status,
    preprocess_data_leveranse,
    preprocess_data_samarbeid,
    hent_leveranse_sistestatus,
    explode_ikke_aktuell_begrunnelse,
    filtrer_bort_saker_på_avsluttet_tidspunkt,
    legg_til_resultatområde,
)
from src.utils.helper import (
    ikke_aktuell_begrunnelse_sortering,
    iatjeneste_og_status_sortering,
)
from src.utils.konstanter import (
    ikkeaktuell_hovedgrunn,
    resultatområder,
)
from src.plots.statistikk import (
    statusflyt,
    gjennomstrømmingstall,
    saker_per_status_per_måned,
    antall_saker_per_status,
    virksomhetsprofil,
)
from src.plots.leveranse import (
    antall_leveranser_per_tjeneste,
    begrunnelse_ikke_aktuell,
    leveranse_per_maaned,
    leveranse_tjeneste_per_maaned,
)
from src.plots.samarbeid import (
    plot_antall_saker_per_antall_samarbeid,
    trakt_antall_samarbeid,
)

PROJECT = "pia-prod-85b2"
DATASET = "pia_bigquery_sink_v1_dataset_prod"

```


```{python}

raw_data_statistikk = load_data_deduplicate(PROJECT, DATASET, "ia-sak-statistikk-v1", "endretAvHendelseId")
raw_data_leveranse = load_data_deduplicate(PROJECT, DATASET, "ia-sak-leveranse-v1", "id, status")
adm_enheter= pd.read_csv("data/administrative_enheter.csv", dtype=str)


```


```{python}
data_statistikk = preprocess_data_statistikk(raw_data_statistikk, adm_enheter)

data_statistikk_resultatområde = data_statistikk[data_statistikk.resultatomrade == resultatområde]
data_status_resultatområde, data_eierskap_resultatområde, _ = split_data_statistikk(data_statistikk_resultatområde)
data_status_resultatområde = preprocess_data_status(data_status_resultatområde)
ikke_aktuell_resultatområde = explode_ikke_aktuell_begrunnelse(data_status_resultatområde)

# Henter data om IA-tjenester

raw_data_leveranse = legg_til_resultatområde(raw_data_leveranse, data_statistikk)
raw_data_leveranse_resultatområde = raw_data_leveranse[raw_data_leveranse.resultatomrade == resultatområde]
data_leveranse_resultatområde = preprocess_data_leveranse(raw_data_leveranse_resultatområde)
data_leveranse_sistestatus_resultatområde = hent_leveranse_sistestatus(data_leveranse_resultatområde)

# Henter data om samarbeid/prosess
raw_data_samarbeid = load_data_deduplicate(PROJECT, DATASET, "samarbeid-bigquery-v1", distinct_colunms="id")
raw_data_samarbeid = legg_til_resultatområde(raw_data_samarbeid, data_statistikk)
raw_data_samarbeid_resultatområde = raw_data_samarbeid[raw_data_samarbeid.resultatomrade == resultatområde]
data_samarbeid_resultatområde = preprocess_data_samarbeid(raw_data_samarbeid_resultatområde, data_statistikk_resultatområde)


# Henter data om spørreundersøkelser
data_spørreundersøkelse = load_data_deduplicate(PROJECT, DATASET, "sporreundersokelse-v1", distinct_colunms="id")
data_spørreundersøkelse = legg_til_resultatområde(data_spørreundersøkelse, data_statistikk)
data_spørreundersøkelse_resultatområde = data_spørreundersøkelse[data_spørreundersøkelse.resultatomrade == resultatområde]

# Henter data om samarbeidsplan
data_samarbeidsplan = load_data_deduplicate(PROJECT, DATASET, "samarbeidsplan-bigquery-v1", distinct_colunms="id")
# samarbeidsplantabellen har ikke saksnummer enda, så vi må legge det til
data_samarbeidsplan = data_samarbeidsplan.merge(
    raw_data_samarbeid[["id", "saksnummer"]].rename({"id": "samarbeidId"}, axis = 1),
    how="left", on="samarbeidId",
)
data_samarbeidsplan = legg_til_resultatområde(data_samarbeidsplan, data_statistikk)
data_samarbeidsplan_resultatområde = data_samarbeidsplan[data_samarbeidsplan.resultatomrade == resultatområde]
```

## Antall samarbeid
{{< include includes/antall_samarbeid_forklaring.qmd >}}

```{python}
trakt_antall_samarbeid(
    data_samarbeid_resultatområde,
    data_spørreundersøkelse_resultatområde,
    data_samarbeidsplan_resultatområde,
)
```

{{< include includes/begrep-forklaring.qmd >}}


## Antall samarbeid per virksomhet

{{< include includes/antall_samarbeid_per_virksomhet_forklaring.qmd >}}

::: {.panel-tabset}
# Antall
```{python}
plot_antall_saker_per_antall_samarbeid(data_samarbeid_resultatområde)
```

# Andel
```{python}
plot_antall_saker_per_antall_samarbeid(data_samarbeid_resultatområde, normalisert=True)
```
:::


## Antall saker per status
::: {.panel-tabset}
# Nåsituasjon
```{python}
antall_saker_per_status(data_status_resultatområde[data_status_resultatområde.aktiv_sak])
```

# Historikk
Vi filtrerer bort saker som ble satt til "Fullført", "Ikke aktuell", eller "Slettet" for over ett år siden.
```{python}
saker_per_status_per_måned(data_status_resultatområde)
```

# Gjennomstrømmingstall
Viser hvor mange saker som går inn og ut av status **Vi bistår**.
Fra status Vi bistår er det mulig å skifte til enten Fullført eller Ikke aktuell.
```{python}
gjennomstrømmingstall(data_status_resultatområde)
```
:::

{{< include includes/sak-forklaring.qmd >}}
{{< include includes/saksstatus-forklaring.qmd >}}


## Leveranser
IA-tjenester er faset ut og erstattet med samarbeidsplanen i Fia.

## Virksomhetsprofil

{{< include includes/virksomhetsprofil_forklaring.qmd >}}

::: {.panel-tabset}

## Før bistand
Saker med nåværende status "Vurderes", "Kontaktes" eller "Kartlegges".\
```{python}
data_input = data_status_resultatområde[data_status_resultatområde.siste_status.isin(["VURDERES", "KONTAKTES", "KARTLEGGES"])]
virksomhetsprofil(data_input)
```

## I bistand
Saker med nåværende status "Vi bistår".\
```{python}
data_input = data_status_resultatområde[data_status_resultatområde.siste_status=="VI_BISTÅR"]
virksomhetsprofil(data_input)
```

## Ikke aktuell
Saker som ble satt til "Ikke aktuell" i de siste 365 dagene.\

```{python}
data_input = data_status_resultatområde[data_status_resultatområde.siste_status=="IKKE_AKTUELL"].drop_duplicates("saksnummer", keep="last")
data_input = filtrer_bort_saker_på_avsluttet_tidspunkt(data_input)
virksomhetsprofil(data_input)
```

## Fullført
Saker som ble satt til "Fullført" i de siste 365 dagene.\

```{python}
data_input = data_status_resultatområde[data_status_resultatområde.siste_status=="FULLFØRT"].drop_duplicates("saksnummer", keep="last")
data_input = filtrer_bort_saker_på_avsluttet_tidspunkt(data_input)
virksomhetsprofil(data_input)
```

:::


## Begrunnelse på ikke aktuell

{{< include includes/begrunnelse_ikke_aktuell_forklaring.qmd >}}

```{python}
begrunnelse_sortering = ikke_aktuell_begrunnelse_sortering(ikke_aktuell_resultatområde)
data_input = filtrer_bort_saker_på_avsluttet_tidspunkt(
    ikke_aktuell_resultatområde[ikke_aktuell_resultatområde.ikkeAktuelBegrunnelse.isin(ikkeaktuell_hovedgrunn.keys())]
)
begrunnelse_ikke_aktuell(data_input, begrunnelse_sortering)
```

{{< include includes/ikke-aktuell-forklaring.qmd >}}

Du finner flere detaljer om statistikk i [Brukerveiledning for Fia på Navet](https://navno.sharepoint.com/sites/intranett-produktomrader-og-prosjekter/SitePages/FIA-brukerveiledning.aspx).
