---
title: "Fia helsesjekk"
subtitle: Helsesjekk for Fia - Fagsystemet for oppfølging av IA-oppdraget i NAV.
title-block-banner: true
title-block-banner-color: white
date: now
date-format: "DD.MM.YYYY HH:mm:ss z"
published-title: "Oppdatert"
author: Team Pia
author-title: "Eier"
execute:
    echo: false
    warning: false
    daemon: false
format:
    dashboard:
        embed-resources: true
        scrolling: false
jupyter: python3
---

```{python}
%load_ext autoreload
%autoreload 2

import os
from helsesjekk import antall_saker_i_vi_bistår, data_denne_perioden

from datetime import datetime

from datahandler import (
    load_data_deduplicate,
    preprocess_data_statistikk,
    split_data_statistikk,
    preprocess_data_status,
    preprocess_data_leveranse,
)

PROJECT = os.environ['GCP_PROJECT']
DATASET = os.environ['DATASET']

raw_data_statistikk = load_data_deduplicate(
    PROJECT, DATASET, "ia-sak-statistikk-v1", "endretAvHendelseId"
)
raw_data_leveranse = load_data_deduplicate(
    PROJECT, DATASET, "ia-sak-leveranse-v1", "id, status"
)

data_leveranse = preprocess_data_leveranse(raw_data_leveranse)

data_statistikk = preprocess_data_statistikk(raw_data_statistikk)
data_status, _ = split_data_statistikk(data_statistikk)
data_status = preprocess_data_status(data_status)
```

```{python}
ANTALL_SAKER_I_VI_BISTÅR = len(data_status[(data_status.status == "VI_BISTÅR") & data_status.aktiv_sak])
```
```{python}
ANTALL_SAKER_I_FULLFØRT = len(data_status[(data_status.status == "FULLFØRT")])
```

```{python}
# Månedstall

(
    startdato,
    sluttdato,
    saker_vi_bistår,
    fullførte_saker,
    antall_tjenester,
) = data_denne_perioden(
    data_status=data_status,
    data_leveranse=data_leveranse,
    startdato=datetime.now(),
    periode="måned",
)
```

```{python}
månedsnavn = [
    "januar",
    "februar",
    "mars",
    "april",
    "mai",
    "juni",
    "juli",
    "august",
    "september",
    "oktober",
    "november",
    "desember",
]

farge = "green" if saker_vi_bistår < fullførte_saker else "light"
```

# Måned

## Row
Totalt akkurat nå

## Row

```{python}
# | content: valuebox
# | title: "Antall saker i 'Vi bistår'"
dict(icon="bullseye", color="light", value=ANTALL_SAKER_I_VI_BISTÅR)

# TODO: Vis gjennomsnitt
# TODO: Vis pil opp eller ned sammenlignet med forrige periode
```

```{python}
# | content: valuebox
# | title: "Antall saker i 'Fullført'"
dict(icon="bullseye", color="light", value=ANTALL_SAKER_I_FULLFØRT)

```


## Row
Tall for `{python} månedsnavn[(startdato.month-1)]` (`{python} str(startdato)` - `{python} str(sluttdato)`)

## Row
```{python}
# | content: valuebox
# | title: "Virksomheter satt til 'Vi bistår' denne måneden"
dict(icon="graph-down", color=farge, value=saker_vi_bistår)
```

```{python}
# | content: valuebox
# | title: "Virksomheter satt til 'Fullført' denne måneden"
dict(icon="graph-up", color=farge, value=fullførte_saker)
```
<!-- TODO: TODO: Dobbelsjekk disse. Ser ikke ut til å stemme med gjennomstrømmingstall i fia datafortelling -->

## Row
Her er "Etterregistrerte" tjenester som har blitt opprettet og levert innen 24 timer

```{python}
forebyggende_arbeidsmiljøarbeid = antall_tjenester["Forebyggende arbeidsmiljøarbeid"]
redusere_sykefravær = antall_tjenester["Redusere sykefravær"]
utvikle_partssamarbeid = antall_tjenester["Utvikle partssamarbeid"]
helse_i_arbeid = antall_tjenester["HelseIArbeid"]
```



| IA-tjeneste | Levert | Opprettet | Etterregistrerte |
|---------|:-----|------:|:------:|
| Forebyggende arbeidsmiljøarbeid | `{python} forebyggende_arbeidsmiljøarbeid["LEVERT"]` | `{python} forebyggende_arbeidsmiljøarbeid["OPPRETTET"]` | `{python} forebyggende_arbeidsmiljøarbeid["ETTERREGISTRERT"]` |
| Redusere sykefravær             | `{python} redusere_sykefravær["LEVERT"]`             | `{python} redusere_sykefravær["OPPRETTET"]`             | `{python} redusere_sykefravær["ETTERREGISTRERT"]`             |
| Utvikle partssamarbeid          | `{python} utvikle_partssamarbeid["LEVERT"]`          | `{python} utvikle_partssamarbeid["OPPRETTET"]`          | `{python} utvikle_partssamarbeid["ETTERREGISTRERT"]`          |
| HelseIArbeid                    | `{python} helse_i_arbeid["LEVERT"]`                  | `{python} helse_i_arbeid["OPPRETTET"]`                  | `{python} helse_i_arbeid["ETTERREGISTRERT"]`                  |


## Row

```{python}
from helsesjekk import plot_historiske_data

plot_historiske_data(data_status=data_status, periode="måned", antall_perioder=12)
```

# Uke

```{python}
# Ukestall
(
    startdato,
    sluttdato,
    saker_vi_bistår,
    fullførte_saker,
    antall_tjenester,
) = data_denne_perioden(
    data_status=data_status,
    data_leveranse=data_leveranse,
    startdato=datetime.now(),
    periode="uke",
)
```


## Row
Totalt akkurat nå

## Row

```{python}
# | content: valuebox
# | title: "Antall saker i 'Vi bistår'"
dict(icon="bullseye", color="light", value=ANTALL_SAKER_I_VI_BISTÅR)

```
```{python}
# | content: valuebox
# | title: "Antall saker i 'Fullført'"
dict(icon="bullseye", color="light", value=ANTALL_SAKER_I_FULLFØRT)
```


## Row
Tall for uke `{python} startdato.isocalendar().week` (`{python} str(startdato)` - `{python} str(sluttdato)`) 

## Row

```{python}
# | content: valuebox
# | title: "Virksomheter satt til 'Vi bistår' denne uken"
dict(icon="graph-down", color="light", value=saker_vi_bistår)
```

```{python}
# | content: valuebox
# | title: "Virksomheter satt til 'Fullført' denne uken"
dict(icon="graph-up", color="light", value=fullførte_saker)
```
<!-- TODO: TODO: Dobbelsjekk disse. Ser ikke ut til å stemme med gjennomstrømmingstall i fia datafortelling -->

## Row
```{python}
forebyggende_arbeidsmiljøarbeid = antall_tjenester["Forebyggende arbeidsmiljøarbeid"]
redusere_sykefravær = antall_tjenester["Redusere sykefravær"]
utvikle_partssamarbeid = antall_tjenester["Utvikle partssamarbeid"]
helse_i_arbeid = antall_tjenester["HelseIArbeid"]
```


## Row
Her er "Etterregistrerte" tjenester som har blitt opprettet og levert innen 24 timer


| IA-tjeneste | Levert | Opprettet | Etterregistrerte |
|---------|:-----|------:|:------:|
| Forebyggende arbeidsmiljøarbeid | `{python} forebyggende_arbeidsmiljøarbeid["LEVERT"]` | `{python} forebyggende_arbeidsmiljøarbeid["OPPRETTET"]` | `{python} forebyggende_arbeidsmiljøarbeid["ETTERREGISTRERT"]` |
| Redusere sykefravær             | `{python} redusere_sykefravær["LEVERT"]`             | `{python} redusere_sykefravær["OPPRETTET"]`             | `{python} redusere_sykefravær["ETTERREGISTRERT"]`             |
| Utvikle partssamarbeid          | `{python} utvikle_partssamarbeid["LEVERT"]`          | `{python} utvikle_partssamarbeid["OPPRETTET"]`          | `{python} utvikle_partssamarbeid["ETTERREGISTRERT"]`          |
| HelseIArbeid                    | `{python} helse_i_arbeid["LEVERT"]`                  | `{python} helse_i_arbeid["OPPRETTET"]`                  | `{python} helse_i_arbeid["ETTERREGISTRERT"]`                  |

## Row

```{python}
from helsesjekk import plot_historiske_data

plot_historiske_data(data_status=data_status, periode="uke", antall_perioder=52)
```