---
title: "Fia datafortelling"
subtitle: Statistikk som viser bruk av Fia - Fagsystemet for oppfølging av IA-oppdraget i NAV.
title-block-banner: true
title-block-banner-color: white
date: now
date-format: "DD.MM.YYYY HH:mm:ss z"
published-title: "Oppdatert"
author: Team Pia
author-title: "Eier"
execute:
    echo: false
    warning: false
format:
    html:
        toc: true
        toc-title: Indeks
        page-layout: full
        embed-resources: true
jupyter: python3
---

**Vi ønsker tilbakemelding fra dere! Meld inn forslag til datafortellingen i [Porten](https://jira.adeo.no/plugins/servlet/desk/portal/541/create/4362).**

Ansvarlig team er [Team Pia](https://teamkatalog.nav.no/team/b347ac99-c382-4e5a-a1dd-532e91110e2a).
Kontakt oss på [slack](https://nav-it.slack.com/archives/C02DL347ZT2) eller på e-post `pia@nav.no`.

Kildekoden finnes på [GitHub](https://github.com/navikt/fia-datafortelling).

<span style="color:red;">
NB! Dette er ikke offisiell statistikk og må ikke deles utenfor NAV.
</span>

```{python}
import os

from code.datahandler import (
    load_data,
    load_data_deduplicate,
    preprocess_data_statistikk,
    split_data_statistikk,
    preprocess_data_status,
    preprocess_data_leveranse,
    kollaps_leveranse_historikk,
    explode_ikke_aktuell_begrunnelse,
)
from code.plots import (
    aktive_saker_per_fylke,
    dager_siden_siste_oppdatering,
    antall_saker_per_status,
    antall_leveranser_per_sak,
    antall_leveranser_per_tjeneste,
    antall_leveranser_per_modul,
    virksomhetsprofil,
    statusflyt,
    begrunnelse_ikke_aktuell,
    hovedbegrunnelse_ikke_aktuell,
    leveranse_tjeneste_per_maaned,
    gjennomstrømmingstall,
)
from code.plots_datakvalitet import saker_per_status_per_måned
from code.tables import moduler_per_maaned
from code.indicators import antall_saker_indicator
from code.helper import (
    modul_sortering,
    ikke_aktuell_begrunnelse_sortering,
)
from code.konstanter import (
    ikkeaktuell_hovedgrunn,
    gamle_ikkeaktuell_hovedgrunn,
)


PROJECT = os.environ['GCP_PROJECT']
DATASET = os.environ['DATASET']
raw_data_statistikk = load_data_deduplicate(PROJECT, DATASET, "ia-sak-statistikk-v1")
raw_data_leveranse = load_data(PROJECT, DATASET, "ia-sak-leveranse-v1")

data_statistikk = preprocess_data_statistikk(raw_data_statistikk)
data_status, data_eierskap = split_data_statistikk(data_statistikk)
data_status = preprocess_data_status(data_status)
data_leveranse = preprocess_data_leveranse(raw_data_leveranse)
data_siste_leveranse = kollaps_leveranse_historikk(data_leveranse)
ikke_aktuell = explode_ikke_aktuell_begrunnelse(data_status)
```


## Antall saker

```{python}
antall_saker_indicator(data_status)
```

::: {.callout-note}

## Forklaring av begrepet "sak" i Fia

En sak i Fia betyr at en virksomhet som er en del av IA-samarbeidet får en begrenset periode med evaluering og mulig hjelp.

En aktiv sak i Fia er en sak som står i status Vurderes, Kontaktes, Kartlegges eller Vi bistår.

En sak er ansett som Avsluttet når den har fått status Ikke aktuell eller Fullført.

En virksomhet kan bare ha én aktiv sak om gangen, men flere saker over tid.
:::


## Statusflyt i Fia
Grafen nedenfor viser antall statusendringer som er registrert i Fia siden starten 10.05.2022.
Gjelder ikke slettede saker og angret statusendringer.

```{python}
statusflyt(data_status)
```
{{< include includes/saksstatus-forklaring.qmd >}}


## Antall saker per status
::: {.panel-tabset}
# Nåsituasjon
```{python}
antall_saker_per_status(data_status[~data_status.siste_status.isin(["SLETTET", "NY"])])
```

# Historikk
```{python}
saker_per_status_per_måned(data_status)
```

# Gjennomstrømmingstall
Viser hvor mange saker som går inn og ut av status Vi bistår.
Fra status Vi bistår er det mulig å skifte til enten Fullført eller Ikke aktuell.
```{python}
gjennomstrømmingstall(data_status)
```
:::


## Antall aktive saker per fylke

```{python}
aktive_saker_per_fylke(data_status)
```


## Dager siden siste oppdatering i Fia
Grafene under viser hvor mange dager det har gått siden siste oppdatering per sak i Fia.
En oppdatering er at noen har tatt eierskap til en sak, en endring av status eller en leveranse som er lagt til eller satt til levert.
Hvis en statusendring blir angret (ved bruk av tilbake-knappen) eller en leveranse blir slettet, telles ikke dette som oppdatering.
Vi viser disse tallene fordelt på status, siden statusene kan ha ulik varighet.
Grafene gir en indikasjon på hvor mange saker som ligger urørt i Fia.

::: {.panel-tabset}
## Alle aktive saker
```{python}
dager_siden_siste_oppdatering(data_status, data_eierskap, data_leveranse)
```
## Vurderes
```{python}
dager_siden_siste_oppdatering(
    data_status[data_status.siste_status=="VURDERES"],
    data_eierskap,
    data_leveranse
)
```
## Kontaktes
```{python}
dager_siden_siste_oppdatering(
    data_status[data_status.siste_status=="KONTAKTES"],
    data_eierskap,
    data_leveranse
)
```
## Kartlegges
```{python}
dager_siden_siste_oppdatering(
    data_status[data_status.siste_status=="KARTLEGGES"],
    data_eierskap,
    data_leveranse
)
```
## Vi bistår
```{python}
dager_siden_siste_oppdatering(
    data_status[data_status.siste_status=="VI_BISTÅR"],
    data_eierskap,
    data_leveranse
)
```
:::


## Leveranser
Når en sak har status "Vi bistår" kan eier av saken registrere hvilke IA-tjenester/moduler som er under arbeid eller levert.
En sak kan ikke gå videre til status "Fullført" før alle registrerte leveranser er satt som levert eller er slettet.
Slettet leveranser vises ikke i grafene under.

::: {.panel-tabset}

## Per tjeneste
```{python}
antall_leveranser_per_tjeneste(data_siste_leveranse)
```

## Per modul
```{python}
modul_sortering = modul_sortering(data_siste_leveranse)
```
::: {.panel-tabset}
## Levert
```{python}
antall_leveranser_per_modul(
    data_siste_leveranse[data_siste_leveranse.status=="LEVERT"], modul_sortering
)
```
## Under arbeid
```{python}
antall_leveranser_per_modul(
    data_siste_leveranse[data_siste_leveranse.status == "UNDER_ARBEID"], modul_sortering
)
```
## Levert og under arbeid
```{python}
antall_leveranser_per_modul(data_siste_leveranse, modul_sortering)
```
:::

## Per sak
Grafen nedenfor viser moduler per sak, i.e., hvor mange moduler som leveres til virksomheter under bistand.
Her gjelder alle saker som har leveranser registert eller kunne ha hatt det, i.e., saker fullført etter det ble mulig å registrere leveranser (mars 2023), og saker i bistand nå.

```{python}
antall_leveranser_per_sak(data_status, data_siste_leveranse)
```

## Per måned
PS: En sak kan ha flere leveranser.
```{python}
leveranse_tjeneste_per_maaned(data_siste_leveranse)
```

## Detaljer
Tabellen viser antall saker per modul og fullført måned, i.e., måneden som modulen ble registrert som levert.
```{python}
moduler_per_maaned(data_siste_leveranse)
```

:::

{{< include includes/leveransestatus-forklaring.qmd >}}


## Virksomhetsprofil
Her vises profilen til virksomheter som er registrert i Fia.
Grafene viser antall saker per antall ansatte, sykefravæarsprosent, sektor, bransjeprogram og de 10 vanligste hovednæringer.
Alle tallene er basert på informasjon vi hadde da de relevante statusendringene skjedde.

Obs.: En virksomhet kan bare ha én aktiv sak om gangen, men flere saker over tid.

::: {.panel-tabset}

## Før bistand
Saker med nåværende status "Vurderes", "Kontaktes" eller "Kartlegges".\
```{python}
data_input = data_status[data_status.siste_status.isin(["VURDERES", "KONTAKTES", "KARTLEGGES"])]
virksomhetsprofil(data_input)
```

## I bistand
Saker med nåværende status "Vi bistår".\
```{python}
data_input = data_status[data_status.siste_status=="VI_BISTÅR"]
virksomhetsprofil(data_input)
```

## Ikke aktuell
Saker med nåværende status "Ikke aktuell".\
```{python}
data_input = data_status[data_status.siste_status=="IKKE_AKTUELL"].drop_duplicates("saksnummer", keep="last")
virksomhetsprofil(data_input)
```

## Fullført
Saker med nåværende status "Fullført".\
```{python}
data_input = data_status[data_status.siste_status=="FULLFØRT"].drop_duplicates("saksnummer", keep="last")
virksomhetsprofil(data_input)
```

:::


## Begrunnelse på ikke aktuell
Her vises andel og antall saker per begrunnelse på ikke aktuell.
Gjelder bare saker med nåværende status "Ikke aktuell", og ikke de sakene som ble angret (ved bruk av tilbake-knappen).
Når en sak settes til "Ikke aktuell" må eieren velge minst en begrunnelse, så en sak kan telles i flere begrunnelser,
og derfor kan andelssummen være større enn 100%.

```{python}
begrunnelse_sortering = ikke_aktuell_begrunnelse_sortering(ikke_aktuell)
```

::: {.panel-tabset}

## Fra alle mulige statuser
```{python}
hovedbegrunnelse_ikke_aktuell(ikke_aktuell)
```

Detaljert begrunnelse
```{python}
begrunnelse_ikke_aktuell(
    ikke_aktuell[ikke_aktuell.ikkeAktuelBegrunnelse.isin(ikkeaktuell_hovedgrunn.keys())],
    begrunnelse_sortering,
)
```

## Fra Vurderes
```{python}
hovedbegrunnelse_ikke_aktuell(ikke_aktuell[ikke_aktuell.forrige_status == "VURDERES"])
```

Detaljert begrunnelse
```{python}
begrunnelse_ikke_aktuell(
    ikke_aktuell[
        ikke_aktuell.ikkeAktuelBegrunnelse.isin(ikkeaktuell_hovedgrunn.keys()) &
        (ikke_aktuell.forrige_status == "VURDERES")
    ],
    begrunnelse_sortering,
)
```

## Fra Kontaktes
```{python}
hovedbegrunnelse_ikke_aktuell(ikke_aktuell[ikke_aktuell.forrige_status == "KONTAKTES"])
```

Detaljert begrunnelse
```{python}
begrunnelse_ikke_aktuell(
    ikke_aktuell[
        ikke_aktuell.ikkeAktuelBegrunnelse.isin(ikkeaktuell_hovedgrunn.keys()) &
        (ikke_aktuell.forrige_status == "KONTAKTES")
    ],
    begrunnelse_sortering,
)
```

## Fra Kartlegges
```{python}
hovedbegrunnelse_ikke_aktuell(ikke_aktuell[ikke_aktuell.forrige_status == "KARTLEGGES"])
```

Detaljert begrunnelse
```{python}
begrunnelse_ikke_aktuell(
    ikke_aktuell[
        ikke_aktuell.ikkeAktuelBegrunnelse.isin(ikkeaktuell_hovedgrunn.keys()) &
        (ikke_aktuell.forrige_status == "KARTLEGGES")
    ],
    begrunnelse_sortering,
)
```

## Fra Vi bistår
```{python}
hovedbegrunnelse_ikke_aktuell(ikke_aktuell[ikke_aktuell.forrige_status == "VI_BISTÅR"])
```

Detaljert begrunnelse
```{python}
begrunnelse_ikke_aktuell(
    ikke_aktuell[
        ikke_aktuell.ikkeAktuelBegrunnelse.isin(ikkeaktuell_hovedgrunn.keys()) &
        (ikke_aktuell.forrige_status == "VI_BISTÅR")
    ],
    begrunnelse_sortering,
)
```

:::

{{< include includes/ikke-aktuell-forklaring.qmd >}}
{{< include includes/ikke-aktuell-forklaring-før-2023-06-30.qmd >}}
