
[project]
name = "src"
version = "0.1.0"
description = "Datafortelling basert på data fra Fia"
authors = [{name="NAV-IT"}]
readme = "README.md"
requires-python = ">=3.13, <3.14"
dependencies = [
    "numpy>=2.2.1,<3.0.0",
    "pandas>=2.2.3,<3.0.0",
    "geopandas>=1.0.1,<2.0.0",
    "plotly>=5.24.1,<6.0.0",
    "db-dtypes>=1.3.1,<2.0.0",
    "google-auth>=2.37.0,<3.0.0",
    "google-cloud-bigquery>=3.27.0,<4.0.0",
    "ipython>=8.31.0,<9.0.0",
    "jupyter-client>=8.6.3,<9.0.0",
    "jupyter-server>=2.15.0,<3.0.0",
    "notebook>=7.3.2,<8.0.0",
    "geojson-rewind>=1.1.0,<2.0.0",
    "pytest>=8.3.4,<9.0.0",
    "ruff>=0.8.6,<0.9.0",
]

[project.urls]
Repository = "https://github.com/navikt/fia-datafortelling.git"

##### Pytest options
[tool.pytest.ini_options]
addopts = "-ra -q" # reduserer output så lenge alle tester består
pythonpath = ["src"]
testpaths = ["tests"]
