[project]
name = "src"
version = "0.1.0"
description = "Datafortelling basert på data fra Fia"
authors = [{name="NAV-IT"}]
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "db-dtypes==1.3.1",
    "geojson-rewind==1.1.0",
    "geopandas==1.0.1",
    "google-auth==2.37.0",
    "google-cloud-bigquery==3.27.0",
    "ipython==8.31.0",
    "jupyter-client==8.6.3",
    "jupyter-server==2.15.0",
    "logging==0.4.9.6",
    "notebook==7.3.2",
    "numpy==2.2.1",
    "pandas==2.2.3",
    "papermill==2.6.0",
    "plotly==5.24.1",
    "requests==2.32.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
Repository = "https://github.com/navikt/fia-datafortelling.git"

##### Pytest options
[tool.pytest.ini_options]
addopts = "-ra -q" # reduserer output så lenge alle tester består
pythonpath = ["src"]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "nbstripout>=0.8.1",
    "pre-commit>=4.1.0",
    "pytest>=8.3.4",
]
