[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

##### Poetry config
[tool.poetry]
name = "src"
version = "0.1.0"
description = "Datafortelling basert på data fra Fia"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.1.3"
pandas = "^2.2.3"
plotly = "^5.24.1"
db-dtypes = "^1.3.1"
google-cloud-bigquery = "^3.27.0"
google-auth = "^2.36.0"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"

[tool.poetry.group.dev.dependencies]
ipython = "^8.30.0"
jupyter-client = "^8.6.3"
jupyter-server = "^2.14.2"
notebook = "^7.3.0"
ruff = "0.8.1"
# An extremely fast Python linter and code formatter, written in Rust.
# Drop-in parity with Flake8, isort, and Black https://docs.astral.sh/ruff/


##### Ruff linter and code formatter
[tool.ruff]
line-length = 120

[tool.ruff.lint.pydocstyle]
convention = "google"

##### Pytest options
[tool.pytest.ini_options]
addopts = "-ra -q" # reduserer output så lenge alle tester består
pythonpath = ["src"]
testpaths = ["tests"]