---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fia-datafortelling-alerts
  namespace: pia
  labels:
    team: pia
spec:
  groups:
    - name: fia-datafortelling-alerts
      rules:
        - alert: FiaDatafortellingNaisjobFeilet
          expr: count_over_time(kube_job_failed{job_name=~"^fia-datafortelling.*",namespace="pia", condition="true"}[10m]) > 0
          for: 1m
          annotations:
            consequence: Datafortellingen ble ikke oppdatert
            action: |-
              Se logger på https://logs.adeo.no -> søk etter `pod:fia-datafortelling AND namespace:pia`
          labels:
            namespace: pia
            severity: warning