apiVersion: nais.io/v1
kind: Naisjob
metadata:
  annotations:
    nais.io/read-only-file-system: "false"
  labels:
    team: pia
  name: fia-datafortelling
  namespace: pia
spec:
  image: {{ image }}
  resources:
    limits:
      memory: 8Gi
    requests:
      memory: 1Gi
  ttlSecondsAfterFinished: 340
  schedule: "0 4 * * *"
  backoffLimit: 2
  accessPolicy:
    outbound:
      external:
      - host: {{ nada_env }}
  gcp:
    bigQueryDatasets:
      - name: pia_bigquery_sink_v1_dataset_prod
        permission: READ
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
  envFrom:
    - secret: fia-quarto-secrets # value is the secret name in Google Secret Manager
  env:
    - name: NADA_ENV
      value: {{ nada_env }}
    - name: QUARTO_ID
      value: {{ quarto_id }}
