apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: pia
  name: fia-datafortelling
  namespace: pia
spec:
  image: {{ image }}
  ttlSecondsAfterFinished: 340
  schedule: "0 7-17/1 * * *"
  backoffLimit: 2
  gcp:
    bigQueryDatasets:
      - name: {{ dataset }}
        permission: READ
  envFrom:
    - secret: fia-quarto-secrets # value is the secret name in Google Secret Manager
  env:
    - name: NADA_ENV
      value: {{ nada_env }}
    - name: QUARTO_ID
      value: {{ quarto_id }}
