---
title: Fia datakvalitet
subtitle: Statistikk som viser datakvalitet i Fia - Fagsystemet for oppfølging av IA-oppdraget i NAV.
title-block-banner: true
title-block-banner-color: white
embed-resources: false
---

```{python}
import os
import pandas as pd

from datafortelling_utils.datahandler import (
    load_data_deduplicate,
    split_data_statistikk,
    beregn_intervall_tid_siden_siste_endring,
    explode_ikke_aktuell_begrunnelse,
)

from datafortelling_utils.dataloader import last_inn_data_statistikk, last_inn_samarbeid

PROJECT = "pia-prod-85b2"
DATASET = "pia_bigquery_sink_v1_dataset_prod"

data_statistikk = last_inn_data_statistikk(
    project=PROJECT,
    dataset=DATASET,
)


data_status, data_eierskap, _ = split_data_statistikk(data_statistikk)

ikke_aktuell = explode_ikke_aktuell_begrunnelse(data_status)

```


## Antall saker per status over tid
```{python}
from datafortelling_utils.statistikk import saker_per_status_over_tid
saker_per_status_over_tid(data_status)
```

## Tid mellom statusendringer
Grafene under viser hvor lenge saker står i en status (før de går over i en annen).
Vi har valgt å dele intervaller på en ujevn måte for å kunne se om endringer tar kort eller lang tid.
Hver bar viser gjeldende periode (fra og med, til).

```{python}
data_status = beregn_intervall_tid_siden_siste_endring(data_status)
```

::: {.panel-tabset}

## Fra Vurderes
::: {.panel-tabset}
## Til Kontaktes
```{python}
from datafortelling_utils.statistikk import dager_mellom_statusendringer
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VURDERES") & (data_status.status=="KONTAKTES")]
)
```
```{python}
from datafortelling_utils.statistikk import median_og_gjennomsnitt_av_tid_mellom_statusendringer
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VURDERES") & (data_status.status=="KONTAKTES")]
)
```
## Til Ikke aktuell
```{python}
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VURDERES") & (data_status.status=="IKKE_AKTUELL")]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VURDERES") & (data_status.status=="IKKE_AKTUELL")]
)
```
## Til Slettet
```{python}
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VURDERES") & (data_status.status=="SLETTET")]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VURDERES") & (data_status.status=="SLETTET")]
)
```
## Til Kontaktes, Ikke aktuell eller Slettet
```{python}
dager_mellom_statusendringer(
    data_status[data_status.forrige_status=="VURDERES"]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[data_status.forrige_status=="VURDERES"]
)
```
:::

## Fra Kontaktes
::: {.panel-tabset}
## Til Kartlegges
```{python}
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="KONTAKTES") & (data_status.status=="KARTLEGGES")]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="KONTAKTES") & (data_status.status=="KARTLEGGES")]
)
```
## Til Ikke aktuell
```{python}
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="KONTAKTES") & (data_status.status=="IKKE_AKTUELL")]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="KONTAKTES") & (data_status.status=="IKKE_AKTUELL")]
)
```
## Til Kartlegges eller Ikke aktuell
```{python}
dager_mellom_statusendringer(
    data_status[data_status.forrige_status=="KONTAKTES"]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[data_status.forrige_status=="KONTAKTES"]
)
```
:::

## Fra Kartlegges
::: {.panel-tabset}
## Til Vi bistår
```{python}
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="KARTLEGGES") & (data_status.status=="VI_BISTÅR")]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="KARTLEGGES") & (data_status.status=="VI_BISTÅR")]
)
```
## Til Ikke aktuell
```{python}
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="KARTLEGGES") & (data_status.status=="IKKE_AKTUELL")]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="KARTLEGGES") & (data_status.status=="IKKE_AKTUELL")]
)
```
## Til Vi bistår eller Ikke aktuell
```{python}
dager_mellom_statusendringer(
    data_status[data_status.forrige_status=="KARTLEGGES"]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[data_status.forrige_status=="KARTLEGGES"]
)
```
:::

## Fra Vi bistår
::: {.panel-tabset}
## Til Fullført
```{python}
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VI_BISTÅR") & (data_status.status=="FULLFØRT")]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VI_BISTÅR") & (data_status.status=="FULLFØRT")]
)
```
## Til Ikke aktuell
```{python}
dager_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VI_BISTÅR") & (data_status.status=="IKKE_AKTUELL")]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[(data_status.forrige_status=="VI_BISTÅR") & (data_status.status=="IKKE_AKTUELL")]
)
```
## Til Fullført eller Ikke aktuell
```{python}
dager_mellom_statusendringer(
    data_status[data_status.forrige_status=="VI_BISTÅR"]
)
```
```{python}
median_og_gjennomsnitt_av_tid_mellom_statusendringer(
    data_status[data_status.forrige_status=="VI_BISTÅR"]
)
```
:::
:::


## Antall saker per eier
Vise antall saker i status "Vi bistår" eller "Fullført" per eier. Gjelder bare siste eier per sak.

```{python}
from datafortelling_utils.statistikk import antall_saker_per_eier
antall_saker_per_eier(data_status)
```


## Antall fullførte saker per måned
```{python}
from datafortelling_utils.statistikk import fullført_per_måned
fullført_per_måned(data_status)
```
