---
title: Bruk av Fia nasjonalt
subtitle: Statistikk som viser Fagsystemet for oppfølging av IA-oppdraget i NAV.
title-block-banner: true
title-block-banner-color: white
---
```{python}
%load_ext autoreload
%autoreload 2

# Imports og konstanter
import os
import pandas as pd

from src.utils.datahandler import (
    load_data_deduplicate,
    preprocess_data_statistikk,
    split_data_statistikk,
    preprocess_data_status,
    preprocess_data_leveranse,
    preprocess_data_samarbeid,
    hent_leveranse_sistestatus,
    explode_ikke_aktuell_begrunnelse,
    filtrer_bort_saker_på_avsluttet_tidspunkt,
)
from src.utils.helper import ikke_aktuell_begrunnelse_sortering
from src.utils.konstanter import ikkeaktuell_hovedgrunn

from src.plots.statistikk import (
    statusflyt,
    gjennomstrømmingstall,
    saker_per_status_per_måned,
    antall_saker_per_status,
    aktive_saker_per_kolonne,
    virksomhetsprofil,
)
from src.plots.leveranse import begrunnelse_ikke_aktuell
from src.plots.samarbeid import (
    plot_antall_saker_per_antall_samarbeid,
    trakt_antall_samarbeid,
)

PROJECT = "pia-prod-85b2"
DATASET = "pia_bigquery_sink_v1_dataset_prod"

```


```{python}
# Preprossesering
# Henter data om hendelser og statusendringer
# med statistikk: sykefravær, bransje, antall ansatte, osv.
raw_data_statistikk = load_data_deduplicate(PROJECT, DATASET, "ia-sak-statistikk-v1", "endretAvHendelseId")
adm_enheter= pd.read_csv("data/administrative_enheter.csv", dtype=str)
data_statistikk = preprocess_data_statistikk(raw_data_statistikk, adm_enheter)

data_status, data_eierskap, _ = split_data_statistikk(data_statistikk)
data_status = preprocess_data_status(data_status)
ikke_aktuell = explode_ikke_aktuell_begrunnelse(data_status)

# Henter data om IA-tjenester
raw_data_leveranse = load_data_deduplicate(PROJECT, DATASET, "ia-sak-leveranse-v1", "id, status")
data_leveranse = preprocess_data_leveranse(raw_data_leveranse)
data_leveranse_sistestatus = hent_leveranse_sistestatus(data_leveranse)

# Henter data om samarbeid/prosess
raw_data_samarbeid = load_data_deduplicate(PROJECT, DATASET, "samarbeid-bigquery-v1", distinct_colunms="id")
data_samarbeid = preprocess_data_samarbeid(raw_data_samarbeid, data_statistikk)

# Henter data om spørreundersøkelser
data_spørreundersøkelse = load_data_deduplicate(PROJECT, DATASET, "sporreundersokelse-v1", distinct_colunms="id")

# Henter data om samarbeidsplan
data_samarbeidsplan = load_data_deduplicate(PROJECT, DATASET, "samarbeidsplan-bigquery-v1", distinct_colunms="id")
```


## Antall samarbeid
{{< include ../includes/antall_samarbeid_forklaring.qmd >}}

```{python}
trakt_antall_samarbeid(
    data_samarbeid,
    data_spørreundersøkelse,
    data_samarbeidsplan,
)
```

{{< include ../includes/begrep-forklaring.qmd >}}


## Antall samarbeid per virksomhet

{{< include ../includes/antall_samarbeid_per_virksomhet_forklaring.qmd >}}

::: {.panel-tabset}
# Antall
```{python}
plot_antall_saker_per_antall_samarbeid(data_samarbeid)
```

# Andel
```{python}
plot_antall_saker_per_antall_samarbeid(data_samarbeid, normalisert=True)
```
:::


## Statusflyt i Fia

{{< include ../includes/statusflyt_i_fia_forklaring.qmd >}}

```{python}
data_input = filtrer_bort_saker_på_avsluttet_tidspunkt(data_status)
statusflyt(data_input)
```

{{< include ../includes/sak-forklaring.qmd >}}
{{< include ../includes/saksstatus-forklaring.qmd >}}


## Antall saker per status
::: {.panel-tabset}
# Nåsituasjon
```{python}
antall_saker_per_status(data_status[data_status.aktiv_sak])
```

# Historikk
Vi filtrerer bort saker som ble satt til "Fullført", "Ikke aktuell", eller "Slettet" for over ett år siden.
```{python}
saker_per_status_per_måned(data_status)
```

# Gjennomstrømmingstall
Viser hvor mange saker som går inn og ut av status **Vi bistår**.
Fra status Vi bistår er det mulig å skifte til enten Fullført eller Ikke aktuell.
```{python}
gjennomstrømmingstall(data_status)
```
:::


## Antall aktive saker per resultatområde
```{python}
aktive_saker_per_kolonne(data_status, "resultatomrade")
```


## Leveranser

{{< include ../includes/leveranser.qmd >}}


## Virksomhetsprofil

{{< include ../includes/virksomhetsprofil_forklaring.qmd >}}

::: {.panel-tabset}

## Før bistand
Saker med nåværende status "Vurderes", "Kontaktes" eller "Kartlegges".\
```{python}
data_input = data_status[data_status.siste_status.isin(["VURDERES", "KONTAKTES", "KARTLEGGES"])]
virksomhetsprofil(data_input)
```

## I bistand
Saker med nåværende status "Vi bistår".\
```{python}
data_input = data_status[data_status.siste_status=="VI_BISTÅR"]
virksomhetsprofil(data_input)
```

## Ikke aktuell
Saker som ble satt til "Ikke aktuell" i de siste 365 dagene.\

```{python}
data_input = data_status[data_status.siste_status=="IKKE_AKTUELL"].drop_duplicates("saksnummer", keep="last")
data_input = filtrer_bort_saker_på_avsluttet_tidspunkt(data_input)
virksomhetsprofil(data_input)
```

## Fullført
Saker som ble satt til "Fullført" i de siste 365 dagene.\

```{python}
data_input = data_status[data_status.siste_status=="FULLFØRT"].drop_duplicates("saksnummer", keep="last")
data_input = filtrer_bort_saker_på_avsluttet_tidspunkt(data_input)
virksomhetsprofil(data_input)
```

:::


## Begrunnelse på ikke aktuell

{{< include ../includes/begrunnelse_ikke_aktuell_forklaring.qmd >}}

```{python}
begrunnelse_sortering = ikke_aktuell_begrunnelse_sortering(ikke_aktuell)
bare_dagens_begrunnelser = ikke_aktuell.ikkeAktuelBegrunnelse.isin(ikkeaktuell_hovedgrunn.keys())
```

::: {.panel-tabset}

## Fra alle mulige statuser
```{python}
data_input = filtrer_bort_saker_på_avsluttet_tidspunkt(
    ikke_aktuell[bare_dagens_begrunnelser]
)
begrunnelse_ikke_aktuell(data_input, begrunnelse_sortering)
```

## Fra Vurderes
```{python}
data_input = filtrer_bort_saker_på_avsluttet_tidspunkt(
    ikke_aktuell[
        bare_dagens_begrunnelser &
        (ikke_aktuell.forrige_status == "VURDERES")
    ]
)
begrunnelse_ikke_aktuell(data_input, begrunnelse_sortering)
```

## Fra Kontaktes
```{python}
data_input = filtrer_bort_saker_på_avsluttet_tidspunkt(
    ikke_aktuell[
        bare_dagens_begrunnelser &
        (ikke_aktuell.forrige_status == "KONTAKTES")
    ]
)
begrunnelse_ikke_aktuell(data_input, begrunnelse_sortering)
```

## Fra Kartlegges
```{python}
data_input = filtrer_bort_saker_på_avsluttet_tidspunkt(
    ikke_aktuell[
        bare_dagens_begrunnelser &
        (ikke_aktuell.forrige_status == "KARTLEGGES")
    ]
)
begrunnelse_ikke_aktuell(data_input, begrunnelse_sortering)
```

## Fra Vi bistår
```{python}
data_input = filtrer_bort_saker_på_avsluttet_tidspunkt(
    ikke_aktuell[
        bare_dagens_begrunnelser &
        (ikke_aktuell.forrige_status == "VI_BISTÅR")
    ]
)
begrunnelse_ikke_aktuell(data_input, begrunnelse_sortering)
```

:::

{{< include ../includes/ikke-aktuell-forklaring.qmd >}}

Du finner flere detaljer om statistikk i [Brukerveiledning for Fia på Navet](https://navno.sharepoint.com/sites/intranett-produktomrader-og-prosjekter/SitePages/FIA-brukerveiledning.aspx).